### ISSUE TITLE
oil generate admin does not warn if files already exist

### ISSUE THREAD

**Issue by kenjis** [fuel/oil#110]
If "app/classes/controller/admin.php" already exists, "oil generate admin" just skips and says nothing.

I hope Error or Notice message, because if there is a model file, "oil generate admin" raises error below:

```
Error: .../app/classes/model/form.php already exists, use -f or --force to override.
```

**Comment by floorish** [comment]
@WanWizard  With that last patch, how am I supposed to generate a new admin section, _without overwriting admin.php_? (and all other generated admin files)

In 1.1/master I was able to do:  `oil g admin test testing:text` and it would skip `admin.php` if it already exists. Exactly what I want, because I could have edited it.

In 1.2/master, when I execute: `oil g admin test testing:text` oil returns:

```
Error: /path/fuel/app/classes/controller/base.php already exists, use -f or --force to override.
```

Ok, so I execute: `oil g admin -f test testing:text`, but _this overwrites admin.php and base.php_! 

I just want to add another section, and keep the general admin files, if they were generated before.

**Comment by bennybobw** [comment]
I also have the issue that floorish mentioned. To add a section to the admin, I have to overwite base and admin.php.

**Comment by WanWizard** [comment]
This has been adressed some time ago.

You can use `-s` or `--skip` to silenty skip over already existing files.
