### ISSUE TITLE
automagic oil refine migrate

### ISSUE THREAD

**Issue by jgdovin** [fuel/oil#13]
by using just oil refine migrate on my machine, migrate was matching the $version === $current version which of course it should not. Maybe this is something weird with my system? but it was not letting me automagically update to the newest version.

I added in a small fix that seems to be working great.

changed:
line #44 of /fuel/app/core/tasks/migrate.php
        else if ($version == $current_version)

To:
        else if (!is_null($version) && $version == $current_version)

**Comment by jgdovin** [comment]
erm after looking at my fix I realized there was a simpler fix.

else if ($version === $current_version)

**Comment by philsturgeon** [comment]
I'd try testing things on your system a whole bunch and send a pull request when its done. Make sure that pull request goes to and from develop branch so you can be sure not to repeat yourself. I remembered having an issue where `else if ($version === $current_version)` was failing due the the CLI picking up the options as a string while config obviously provided an integer. 

Check it out and pull request when its done so we can be sure things are right. Otherwise I have to try and recreate your exact scenario and you've not given me enough to do that :)
