### ISSUE TITLE
Problem with mysql enum column while migrating after fromdb model creation

### ISSUE THREAD

**Issue by mdegayon** [fuel/oil#189]
Well, I've got a table  like:

CREATE TABLE `planningagents` (
  `id` int(255) unsigned NOT NULL AUTO_INCREMENT,
  `jour` date NOT NULL,
  `heures` int(2) NOT NULL,
  `am_pm` enum('matin','apres-midi') NOT NULL,
  `id_agent` int(255) unsigned NOT NULL,
  `id_cpt_gid` int(255) unsigned NOT NULL,
  `date_creation` date NOT NULL,
  `derniere_maj` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

that I created from mysql. After, I ran;

php oil refine fromdb:model planningagents

That I guess worked just fine, since it created the next model class:

class Model_Planningagent extends \Orm\Model
{

```
protected static $_properties = array(
    'id',
    'jour',
    'heures',
    'am_pm',
    'id_agent',
    'id_cpt_gilda',
    'date_creation',
    'derniere_maj',
);
```

}

So, I ran from command line:

'php oil refine migrate', 

that returned the next error:

"42000 - SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near
OT NULL,
        `id_agent` int(11) NOT NULL,
        `id_cpt_gilda` int(11) NOT NULL,
        `date' at line 5 with query: "CREATE TABLE IF NOT EXISTS`planningagents`(
`id`int(11) NOT NULL AUTO_INCREMENT,
`jour`date NOT NULL,
`heures`int(2) NOT NULL,
`am_pm`enum NOT NULL,
`id_agent`int(11) NOT NULL,
`id_cpt_gilda`int(11) NOT NULL,
`date_creation`date NOT NULL,
`derniere_maj`date NOT NULL,
        PRIMARY KEY`id`(`id`)
) DEFAULT CHARACTER SET utf8;" in COREPATH/classes/database/pdo/connection.php on line 175"

There's an error in this query. It would have included a line like: 

  `am_pm` enum('matin','apres-midi') NOT NULL,

instead of 

```
    `am_pm` enum NOT NULL,
```

I succeed to run the migration command by addind some lines to db/orm/connection.php file. But it wasn't a very stylish solution. 

Regards.

**Comment by WanWizard** [comment]
Whether or not the FromDB task returns anything useful is largely dependent on the database driver used, and the RDMBS platform.

From the error I can see you're using PDO. Unfortunately, due to the fact the PDO driver is a generic and RDBMS independent driver, it uses a "DESCRIBE" command to get information about columns. Which is not very detailed, for example no type is returned.

This is why the property list in the model only lists the column names, and no extra options, and why you only have the basic data type, with little constraint information. This can't be helped.

If you switch to the MySQLi driver (when using fromdb), it will work fine, as that will use MySQL specific commands which return much more information.
