### ISSUE TITLE
Odd error with CamelCase

### ISSUE THREAD

**Issue by Marco105** [fuel/oil#192]
I buid this command:

php oil generate scaffold someNews titre:string permalien:varchar[250] contenu:text

php oil refine migrate

from the page in FF, i got that:

Fuel\Core\Database_Exception [ Error ]: SQLSTATE[42S02]: Base table or
view not found: 1146 Table 'fuel_dev.some_news' doesn't exist with
query: "SELECT `t0`.`id` AS `t0_c0`, `t0`.`titre` AS `t0_c1`,
`t0`.`permalien` AS `t0_c2`, `t0`.`contenu` AS `t0_c3`,
`t0`.`created_at` AS `t0_c4`, `t0`.`updated_at` AS `t0_c5` FROM
`some_news` AS `t0`"

Why table's name become some_news instead someNews !!??

**Comment by WanWizard** [comment]
Looks like the ORM model generated doesn't include the $_table property to hardcode the table name used for the model. 

So the model follows the rules for guessing the table name, which is: lowercase, plural, underscored.

Quickest solution is to add a `protected $_table_name = 'someNews';` to your Model in case you have a non-standard naming convention for database tables. Note that if you use the generated migration, the tablename is 'somenews', not 'someNews', as migrations convert it to lower case.

This can't be fixed in oil, as not everyone has the same non-standard naming conventions.
