### ISSUE TITLE
OIL migrate task broken?

### ISSUE THREAD

**Issue by AlbinoGeek** [fuel/oil#198]
OIL migrations are currently broken `oil refine migrate` will return an error "uncaught exception: No task migrate"

Whereas oil refine migrate --all will work as expected.

**Comment by WanWizard** [comment]
```
[hverton@catwoman] $ env FUEL_ENV=local php oil refine migrate
Already on the latest migration for app:default.
```

works fine here...

I've checked the code. There is no message "No task [taskname]". There is an exception "Task [taskname] does not exist". I assume you mean that?

You get this error if the Finder has gone through your entire installation, looking for a "tasks" folder with a file "migrate.php" in it. 

Since that is in fuel/core/tasks, and the Finder can run so fuel/core is where it should be, I'd say given all the issues you have, I think you should seriously look at your installation. There are plenty of users running Fuel on Windows, so that can't be it.

**Comment by AlbinoGeek** [comment]
This last issue was due to "it's Windows"; I didn't pay enough attention to the error message:

```
Task migrate
does not exist
```

Notice the newline?  I hate WIndows ....

**Comment by WanWizard** [comment]
Hmm.... Guess that makes two of us... :grinning:
