### ISSUE TITLE
Adding more PHPUnit options to oil

### ISSUE THREAD

**Issue by mattm458** [fuel/oil#20]
I actually just forked oil to work on this, but I thought I'd post about it here and see what the consensus is.

My desire to do this came from wanting to use the exclude-group option in PHPUnit in a site I'm working on, so I put it in oil. But there's more useful options in PHPUnit that don't get passed in Oil, and a help menu that explains them all. Oil should have at least some of these extra options.

**Comment by philsturgeon** [comment]
Go for it? The main reason for embedding Oil is that we want to be able to control it, bootstrap it and do as we wish in the future. Instead of simply using PHPUnit we are using the logic of PHPUnit as an engine to do whatever we want.

Now, if you think more options should be added and have a fork of Oil I'd suggest you look into a way to pass through any and all options to the command line. Or create a list of options that should be checked for and added in specifically if present.

The help menu should be part of `oil test --help` as we may of course have our own options to explain.
