### ISSUE TITLE
Oil not setting up ORMAuth model

### ISSUE THREAD

**Issue by mogusbi** [fuel/oil#202]
When executing the `oil refine migrate --packages=auth` command, ORMAuth tables are set up in the database as expected, however, no model(s) is created therefore any time you try to access a page generated using the `oil generate admin blah blah:string` command, you're met with a log in screen but if you try to log in, you are met with an error saying that the "Class 'Model_User' [was] not found"

The error is coming from here: APPPATH/classes/controller/admin.php @ line 50

Line 50: $current_user = Model_User::find_by_username(Auth::get_screen_name());

**Comment by WanWizard** [comment]
This issue here is:
- oil admin assumes you did a `oil generate admin user ...` first which would create the user model
- oil admin assumes you're using Simpleauth

This means not only the Model call is incorrect, also the admin group check will fail, as permissions work differently in Ormauth, compared to Simpleauth.
