### ISSUE TITLE
Scaffolding creates invalid controller name

### ISSUE THREAD

**Issue by pim** [fuel/oil#33]
Hey, this is my first issue opened ever, so please don’t kill me if I’m doing something wrong :)

The problem I encountered is connected with scaffolding. When I type something like this:
`oil g scaffold animal name:string type:text`

Oil creates controller file named `animals.php`, but puts `class Controller_Animal extends Controller_Template`. The name of the file and inside the file are different and it causes some problems. I have to correct it by hand to get it working.

**Comment by philsturgeon** [comment]
You did something wrong but I'm not going to kill you! 

There was a bug in v1.0 annoyingly, that was introduced as a fix to some other obscure problem and was not tested enough before release WEAK. (but my fault)

The thing you did "wrong" is to post an issue on something already fixed in develop. It's usually a good idea to check that out first as more often than not we'll have fixed the issue already.

@dhorrigan: Can you get the v1.0.1 fix out now please? It's two weeks late...

**Comment by pim** [comment]
Aww, sorry about this. Thanks for help, though.
