### ISSUE TITLE
Problems with ErrorException, can't avoid an error in Oil Refine

### ISSUE THREAD

**Issue by darklow** [fuel/oil#71]
I have latest 1.1/develop version.
I think there is something wrong with error exception in oil. 
This code for example:

``` php
try{
    $handle = @fopen('http://bad.location', "rb");
}
catch(Exception $e)
{

}
```

There is no way i can avoid errors and continue my script. On every error fopen throws scripts exits.
Are there any workarounds?

This same scripts works perfectly in usual environment, but runing Oil refine always produces errors you cannot handle or avoid and script exits. 

I think there should be a way to display errors and notices, but to avoid exiting the script, now it always exists on smallest notice or warning.

Thanks

**Comment by WanWizard** [comment]
fopen() doesn't throw an error (hardly any PHP internal function does), it generates a PHP error. As it is not an exception, it can not be caught. The error suppression should cause it to continue in oil too.

Besides that, any PHP code (oil script or otherwise) that causes notices or warnings should be rewritten so that doesn't happen, supressing or ignoring them is bad practice.
